# TPM Defaults
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Status Bar

# Sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

# Auto-Name Window
set -g @plugin 'ofirgall/tmux-window-name'

# Clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# Smart Picking
set -g @plugin 'Morantron/tmux-fingers'

# Launcher
set -g @plugin 'tmux-plugins/tmux-open'

# FZF
set -g @plugin 'sainnhe/tmux-fzf'

# VIM keys
set -g @plugin 'christoomey/vim-tmux-navigator'

# Theme
set -g @plugin 'dracula/tmux'

# Dracula Config
set -g @dracula-show-powerline false
set -g @dracula-show-flags false
set -g @dracula-show-left-icon session
set -g @dracula-plugins "cpu-usage ram-usage battery"
set -g @dracula-military-time true
set -g @dracula-show-timezone false
set -g @dracula-day-month false

set -g status-position top

# Fix Terminal Key (nvim)
bind-key -n C-/ send-keys C-/

run '~/.tmux/plugins/tpm/tpm'
